version: '3.8'

services:
  postgres_db_lg:
    container_name: "jellylink_postgresql_lg"
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_DB: jellylink_db_lg
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_lg:/var/lib/postgresql/data

  postgres_db:
    container_name: "jellylink_postgresql_dt"
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_DB: jellylink_db_dt
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8888:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:
  postgres_lg:
  pgadmin_data: