version: '3.8'

services:
  account_db:
    container_name: "postgresql_account_db"
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - account_db_volume:/var/lib/postgresql/data

  data_db:
    container_name: "postgresql_data_db"
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_DB: data_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - data_db_volume:/var/lib/postgresql/data

  session_cache:
    container_name: "redis_session_db"
    iamge: redis:7.2.4

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8888:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  data_db_volume:
  account_db_volume:
  pgadmin_data: