version: '3.8'

services:
  cache_db:
    container_name: cache_redis
    image: redis:7.2.4-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - cache-data:/data

  game_db:
    container_name: game_mongo
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: server_db
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - game-data:/data/db
      - game-data_config:/data/configdb
      - ./start/:/docker-entrypoint-initdb.d/:ro


  server_app_1:
    image: server-app:latest
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  game-data:
  game-data_config:

  cache-data: